name: CD

on:
  push:
    branches:
      - main

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest

    steps:
      - name: Install Dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: SonarCloud Scan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      
      - name: Build for GitHub Pages
        run: npm run build

      - name: Deploy to GitHub Pages
        run: |
          git checkout --orphan gh-pages
          git rm -rf .
          cp -r build/. .
          git add .
          git commit -m "GitHub Pages deployment"
          git push origin gh-pages --force
          git checkout main
